services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      MARIADB_DATABASE: papers_db
      MARIADB_USER: admin
      MARIADB_PASSWORD: 1234
      MARIADB_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
